# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t travisimages/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run travisimages/react-test npm test -- --coverage

after_success:
  - docker build -t travisimages/multi-client ./client
  - docker build -t travisimages/multi-nginx ./nginx
  - docker build -t travisimages/multi-server ./server
  - docker build -t travisimages/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push travisimages/multi-client
  - docker push travisimages/multi-nginx
  - docker push travisimages/multi-server
  - docker push travisimages/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-711629017260
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESSS_KEY
  secret_access_key: 
    secure: AWS_SECRET_KEY
  